server:
  port: 8081

spring:
  application:
    name: user

  datasource:
    name: test
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/test?useUnicode=true&characterEncoding=UTF8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:feng}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 64
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-wait: 5s

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 47.107.47.66:9300
      repositories:
        enabled: true
