server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #启用服务发现 可以实用服务名称自动路由到指导的服务 并自动去掉服务名
          lower-case-service-id: true #使用小写
      routes:
        - id: userApi
          uri: lb://user
          filters:
            - StripPrefix=1 #自己配置的需要过滤前缀
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1  #每秒流量
                redis-rate-limiter.burstCapacity: 2  #突发流量
                key-resolver: "#{@userKeyResolver}"  #限流的key
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fail
          predicates:
            - Path=/userApi/**


  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG